@JWTAuth_HostAddress = https://localhost:7218

POST {{JWTAuth_HostAddress}}/api/user/SignUp?username=povfri&password=123456

###

GET {{JWTAuth_HostAddress}}/api/user/LogIn?username=povfri&password=123456

###

GET {{JWTAuth_HostAddress}}/api/user/GetUser?username=povfri
Authorization: Bearer ***

###

GET {{JWTAuth_HostAddress}}/GetCarID/1
Authorization: Bearer ***
###

GET {{JWTAuth_HostAddress}}/GetCars
Authorization: Bearer ***

###
