@Notepad.Main_HostAddress = https://localhost:7123
@jwt = ***
@username = ***
@password = ***
@regUsername = ***
@regPassword = ***

POST {{Notepad.Main_HostAddress}}/api/user/LogIn?username={{username}}&password={{password}}

###

POST {{Notepad.Main_HostAddress}}/api/user/Register?username={{regUsername}}&password={{regPassword}}

###
