@Task1_HostAddress = https://localhost:7118

GET {{Task1_HostAddress}}/Product/
Accept: application/json

###

POST {{Task1_HostAddress}}/AddProduct/
Accept: */*
Content-Type: application/json

{
    "id": 4,
    "name": "Onion",
    "price": 0.99
}

###

DELETE {{Task1_HostAddress}}/RemoveByID/4

###

GET {{Task1_HostAddress}}/GetProductByName/Onion

###

GET {{Task1_HostAddress}}/product/GetProductsByPrice/4-6

###

GET {{Task1_HostAddress}}/product/GetProductsByPrice/0.6-0.4

###