@Task1_HostAddress = https://localhost:7126

GET {{Task1_HostAddress}}/GetAllCars

###

GET {{Task1_HostAddress}}/GetCarsByColor?color=Green

###

GET {{Task1_HostAddress}}/GetCarsByColor?color=Black

###

POST {{Task1_HostAddress}}/AddNewCar
Content-Type: application/json

{
  "Manufacturer" : "Subaru",
  "Color" : "Blue"
}

###

POST {{Task1_HostAddress}}/UpdateCar?id=4
Content-Type: application/json

{
  "Manufacturer" : "Subaru",
  "Color" : "Yellow"
}

###

DELETE {{Task1_HostAddress}}/DeleteCar/3

###
